---
- hosts: localhost 
  become: true
  become_user: ubuntu
  become_method: sudo

  tasks:
   - name: Create Folder
     file:
       path: /home/ubuntu/tomcat
       state: directory
       mode: 0755
